version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    environment:
      - NODE_ENV=production
      - HTTP_SERVER_PORT=4201
    volumes:
      - ./backend/data:/app/data
      - ./backend/config:/app/config
    restart: always

  final-math-frontend:
    build:
      context: ./final-math-frontend
      dockerfile: apps/final-math-frontend/Dockerfile
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - backend

  # viewer:
  #   build:
  #     context: ./viewer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4001:4001"
  #   restart: always

  # react-viewer:
  #   build:
  #     context: ./react-viewer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:80"
  #   restart: always
  #   depends_on:
  #     - backend
